### ISSUE TITLE
readme 中的示例， $mailer  应去掉  $

### ISSUE THREAD

**Issue by liuxiaofan** [phalapi/PHPMailer#1]

**Comment by VitaminVI** [comment]
使用示例
\PhalApi\DI()->$mailer->send('chanzonghuang@gmail.com', 'Test PHPMailer Lite', 'something here ...');
应改为
\PhalApi\DI()->mailer->send('chanzonghuang@gmail.com', 'Test PHPMailer Lite', 'something here ...');
即去掉mailer前的$符

**Comment by phalapi** [comment]
已更正。
